[tool.poetry]
name = "news_crawler"
version = "0.1.0"
description = ""
authors = [" "]

[tool.poetry.dependencies]
python = ">3.9,<4"
bs4 = "^0.0.1"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
