on:
  schedule:
    - cron: "0 4,7 * * *"
  push:
    branches: [master]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: |
          git fetch origin
          git switch master
      - run: |
          git switch --orphan new
          git restore -s master .
          pip install poetry && poetry install
      - run: |
          poetry run python ./src/main.py
      - run: |
          git rm -rf --ignore-unmatch .
          git add -f public/ .github/
      - run: |
          git commit -m "$(TZ="Asia/Taipei" date '+%Y/%m/%d %H:%M:%S')"
          git push origin new:public -f
